# ============================================================
#  AXIOM · Training Data
#  Intents + example utterances for the NLP model
# ============================================================

training_data = [

    # ── greet ────────────────────────────────────────────────
    ("hi",                              "greet"),
    ("hello",                           "greet"),
    ("hey",                             "greet"),
    ("hey there",                       "greet"),
    ("hello there",                     "greet"),
    ("hi there",                        "greet"),
    ("good morning",                    "greet"),
    ("good afternoon",                  "greet"),
    ("good evening",                    "greet"),
    ("what's up",                       "greet"),
    ("sup",                             "greet"),
    ("howdy",                           "greet"),
    ("yo",                              "greet"),
    ("greetings",                       "greet"),
    ("hiya",                            "greet"),

    # ── who_are_you ──────────────────────────────────────────
    ("who are you",                     "who_are_you"),
    ("what are you",                    "who_are_you"),
    ("tell me about yourself",          "who_are_you"),
    ("introduce yourself",              "who_are_you"),
    ("what is your name",               "who_are_you"),
    ("what's your name",                "who_are_you"),
    ("who am i talking to",             "who_are_you"),
    ("are you a bot",                   "who_are_you"),
    ("are you an ai",                   "who_are_you"),
    ("are you human",                   "who_are_you"),
    ("what kind of ai are you",         "who_are_you"),
    ("describe yourself",               "who_are_you"),
    ("tell me who you are",             "who_are_you"),
    ("what should i call you",          "who_are_you"),
    ("do you have a name",              "who_are_you"),

    # ── who_made_you ─────────────────────────────────────────
    ("who made you",                    "who_made_you"),
    ("who created you",                 "who_made_you"),
    ("who built you",                   "who_made_you"),
    ("who is your creator",             "who_made_you"),
    ("who designed you",                "who_made_you"),
    ("who developed you",               "who_made_you"),
    ("who is behind you",               "who_made_you"),
    ("who programmed you",              "who_made_you"),
    ("who is your developer",           "who_made_you"),
    ("who invented you",                "who_made_you"),
    ("who coded you",                   "who_made_you"),
    ("who is your maker",               "who_made_you"),
    ("who wrote you",                   "who_made_you"),
    ("who is responsible for you",      "who_made_you"),
    ("where do you come from",          "who_made_you"),

    # ── what_can_you_do ──────────────────────────────────────
    ("what can you do",                 "what_can_you_do"),
    ("how can you help me",             "what_can_you_do"),
    ("what are your capabilities",      "what_can_you_do"),
    ("what do you do",                  "what_can_you_do"),
    ("how do you work",                 "what_can_you_do"),
    ("what are you good at",            "what_can_you_do"),
    ("what features do you have",       "what_can_you_do"),
    ("what are your functions",         "what_can_you_do"),
    ("can you help me",                 "what_can_you_do"),
    ("what help can you give",          "what_can_you_do"),
    ("tell me what you can do",         "what_can_you_do"),
    ("what are you able to do",         "what_can_you_do"),
    ("what is your purpose",            "what_can_you_do"),
    ("what were you made for",          "what_can_you_do"),
    ("show me what you can do",         "what_can_you_do"),

    # ── farewell ─────────────────────────────────────────────
    ("bye",                             "farewell"),
    ("goodbye",                         "farewell"),
    ("see you",                         "farewell"),
    ("see ya",                          "farewell"),
    ("later",                           "farewell"),
    ("take care",                       "farewell"),
    ("good night",                      "farewell"),
    ("until next time",                 "farewell"),
    ("catch you later",                 "farewell"),
    ("cya",                             "farewell"),
    ("talk to you later",               "farewell"),
    ("i'm leaving",                     "farewell"),
    ("i have to go",                    "farewell"),
    ("peace out",                       "farewell"),
    ("so long",                         "farewell"),

    # ── fallback (out-of-scope examples) ─────────────────────
    ("what is the weather",             "fallback"),
    ("tell me a joke",                  "fallback"),
    ("what time is it",                 "fallback"),
    ("calculate 2 plus 2",              "fallback"),
    ("open youtube",                    "fallback"),
    ("play some music",                 "fallback"),
    ("set a timer",                     "fallback"),
    ("what is the capital of france",   "fallback"),
    ("translate hello to spanish",      "fallback"),
    ("search google for cats",          "fallback"),
]
